version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinitum-backend
    ports:
      - "3000:8080"
    env_file:
      - .env
    restart: always